import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <Providers>
          <div className="bg-gray-100 w-full px-5 py-3 flex justify-between items-center">
            <Link href="/" className="hover:text-blue-600">
              Home
            </Link>
            <Link href="/logout" className="hover:text-blue-600">
              Log out
            </Link>
          </div>

        <div className="flex flex-1">
          <div className="w-60 h-screen bg-gray-800 text-white flex flex-col">
            <div className="px-5 py-3 font-bold">Menu</div>
            <Link href="/categories" className="px-5 py-2 hover:bg-gray-700">
              Categories
            </Link>
            <Link href="/expenses" className="px-5 py-2 hover:bg-gray-700">
              Expenses
            </Link>
            <Link href="/reports" className="px-5 py-2 hover:bg-gray-700">
              Reports
            </Link>
          </div>

          <div className="p-5 flex-1">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
